#!/usr/bin/env ruby
#-*- coding:utf-8 -*-
#コマンドの定義、メソッドの実行

require './getMomokuro'

arg = ARGV[0]

mkz = GetMomokuro.new

case arg
when "走れ！" , "走れ" 
	mkz.hashire
when "行くぜっ！怪盗少女" , "怪盗少女"
	mkz.kaitousyouzyo
when "ココナツ","ココ☆ナツ"
	mkz.kokonatsu
when "ChaiMax","Chai Max","chaimax","chai max","chai maxx","chaimaxx"
	mkz.chaimax
when "キミとセカイ","きみとせかい"
	mkz.kimitosekai
when "全力少女"
	mkz.zenryokusyozyo
when "ピンキージョーンズ","ピンキー","ぴんきーじょーんず"
	mkz.pinkey
when "ミライボール","みらいぼーる"
	mkz.miraiball
when "未来へススメ","未来へすすめ","未来へ進め","みらいへすすめ"
	mkz.miraihesusume
when "Z伝説","Z伝説～終わりなき革命～","z伝説","z伝説～終わりなき革命～"
	mkz.zdensetsu
when "このうた","コノウタ"
	mkz.konouta
when "きみのあと","キミノアト"
	mkz.kiminoato
when "ももクロのニッポン万歳","ニッポン万歳","にっぽんばんざい"
	mkz.nihonbanzai
when "だってあーりんなんだもん","あーりんなんだもん"
	mkz.arinnadamon
when "労働讃歌"
	mkz.rodousanka
when "サンタさん","サンタサン"
	mkz.santasan
when "help"
	mkz.help
else
	puts "そのコマンドは存在しません。"
end